### ISSUE TITLE
Tool change with vcarve clearance tool

### ISSUE THREAD

**Issue by mrnevitt** [neilferreri/V-Carve-PPs#1]
I added your PP and was going to test it out on a small sign and got the attached error.  Apparently it doesn't like the clearance tool with a vcarve tool path.  But I also got the error when I took the clearance tool path out and put in a simple profile cut with a different bit size.

![Toolchange PP error](https://user-images.githubusercontent.com/36103986/71486377-0b125900-27e4-11ea-9043-58bc276ce565.png)

**Comment by neilferreri** [comment]
Your tools are labeled with the same number. You'll just need to change the tool numbers. You can't export a job with multiple tool #1s.
See this:
https://community.carbide3d.com/uploads/default/original/3X/3/7/37fd6f61234debbf9f50a3f9414fd464accc12f7.gif

**Comment by mrnevitt** [comment]
Ah!!  Such an easy fix. Sorry about that. I’ve always done separate tool
paths so never noticed or used the tool numbers like that. Thanks for the
quick reply!!!

Mike
