### ISSUE TITLE
Not an issue but possible addition

### ISSUE THREAD

**Issue by gixxergreko** [neilferreri/V-Carve-PPs#4]
I was wondering if you would be adapting you PP for use with Vectric's new laser module.  Thanks. John

**Comment by neilferreri** [comment]
Hey John,
If I work something up, will you be able to test it?
What's your machine setup like?

EDIT: Can you try the attached?
EDIT 2 : Link to file added below.

**Comment by gixxergreko** [comment]
Shapeoko 3 XL with HDZ, Carbide3d touch probe and Bitsetter, J Tech 7w
laser, pwncnc dust boot, Beaver CNC limit switches(Hall Effect). I use
Vectric Aspire and Carbide Motion. I also us UGS on occasion.

**Comment by gixxergreko** [comment]
Neil,
I just tried installing you latest PPs and got the following errors which I
screen shot. The version I had installed previously (from April or May I
think) didn't have any issues. Not sure if anyone else is having the same
issue. Thanks.
John

**Comment by neilferreri** [comment]
Hey John,
I'm not seeing any screenshot.
I sent you a message on Carbide's community forum.

**Comment by neilferreri** [comment]
Laser Module Support added to post processor [here](https://github.com/neilferreri/V-Carve-PPs/tree/master/LaserModule).
Confirmed to work with 10.5 with workaround for Vectric bug.
